FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src

COPY ["Uis.Server.csproj", "./"]
RUN dotnet restore "Uis.Server.csproj"

COPY . .
RUN dotnet build "Uis.Server.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Uis.Server.csproj" -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Uis.Server.dll"]
